baseURL = "https://kaiasaoka.github.io"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

#  [[menu.header]]
#  name = "About"
#  URL = "#about"
#  weight = 2

  [[menu.header]]
  name = "Experience"
  URL = "/experience"
  weight = 3

  [[menu.header]]
  name = "Projects"
  URL = "/projects"
  weight = 4

  [[menu.header]]
  name = "Blog"
  URL = "/blogsite"
  weight = 6

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 7

  [[menu.footer]]
  name = "Home"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Experience"
  URL = "/experience"
  weight = 3

  [[menu.footer]]
  name = "Projects"
  URL = "/projects"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "Kai"
    text2 = "Asaoka"

  [params.footer]
      copyright = "Â© Kai Asaoka"
        
# Enable unsafe rendering for Goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true